repoRoot = fileparts(fileparts(mfilename('fullpath')));
cleanupRepoPath = addPathIfNeeded(repoRoot);
cleanupClassAnnotationsPath = addPathIfNeeded('/Users/jearly/Documents/OceanKitRepositories/class-annotations'); %#ok<NASGU>

helperRoot = tempname;
mkdir(helperRoot);
cleanupHelperRoot = onCleanup(@() removeDirectoryIfPresent(helperRoot)); %#ok<NASGU>
cleanupHelperPath = addPathIfNeeded(helperRoot); %#ok<NASGU>

helperWidgetClassName = 'DocumentationTypeHelperWidget';
typedClassName = 'DocumentationTypedPropertyTestClass';
variableSizedClassName = 'DocumentationVariableSizedPropertyTestClass';
typedAnnotatedClassName = 'DocumentationTypedAnnotatedPropertyTestClass';
annotationOnlyClassName = 'DocumentationAnnotationOnlyTypeTestClass';
untypedClassName = 'DocumentationUntypedPropertyTestClass';
hiddenClassName = 'DocumentationHiddenTypedPropertyTestClass';
declaredClassName = 'DocumentationDeclaredTypedPropertyTestClass';

writeTextFile(fullfile(helperRoot, strcat(helperWidgetClassName, '.m')), { ...
    sprintf('classdef %s < handle', helperWidgetClassName), ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(typedClassName, '.m')), { ...
    sprintf('classdef %s < handle', typedClassName), ...
    '    properties', ...
    '        % Typed property summary.', ...
    '        %', ...
    '        % Typed property discussion.', ...
    '        %', ...
    '        % - Topic: Inspect typed properties', ...
    '        value (1,1) double = 0', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(variableSizedClassName, '.m')), { ...
    sprintf('classdef %s < handle', variableSizedClassName), ...
    '    properties', ...
    '        % Variable-sized property summary.', ...
    '        %', ...
    '        % Variable-sized property discussion.', ...
    '        %', ...
    '        % - Topic: Inspect typed properties', ...
    '        values (1,:) double = 1', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(typedAnnotatedClassName, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', typedAnnotatedClassName), ...
    '    properties', ...
    '        % Reflected widget summary.', ...
    '        %', ...
    '        % Reflected widget discussion.', ...
    '        %', ...
    '        % - Topic: Inspect typed properties', ...
    sprintf('        widget (1,1) %s = %s()', helperWidgetClassName, helperWidgetClassName), ...
    '    end', ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CAObjectProperty(''widget'', ''Annotated widget summary.'', className=''WrongWidget'', sizeText=''nonempty vector'', detailedDescription=''- Topic: Annotated topic'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''widget''};', ...
    '        end', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(annotationOnlyClassName, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', annotationOnlyClassName), ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CAObjectProperty(''virtualValue'', ''Virtual value summary.'', className=''TrajectorySpline'', sizeText=''nonempty vector'', detailedDescription=''- Topic: Virtual topic'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''virtualValue''};', ...
    '        end', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(untypedClassName, '.m')), { ...
    sprintf('classdef %s < handle', untypedClassName), ...
    '    properties', ...
    '        % Untyped property summary.', ...
    '        %', ...
    '        % Untyped property discussion.', ...
    '        %', ...
    '        % - Topic: Inspect untyped properties', ...
    '        value', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(hiddenClassName, '.m')), { ...
    sprintf('classdef %s < handle', hiddenClassName), ...
    '    properties (Access = private)', ...
    '        % Hidden typed property summary.', ...
    '        %', ...
    '        % Hidden typed property discussion.', ...
    '        %', ...
    '        % - Topic: Inspect hidden properties', ...
    '        secretValue (1,1) double = 1', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(declaredClassName, '.m')), { ...
    sprintf('classdef %s < handle', declaredClassName), ...
    '    properties', ...
    '        % Declared typed property summary.', ...
    '        %', ...
    '        % Declared typed property discussion.', ...
    '        %', ...
    '        % - Topic: Inspect declared properties', ...
    '        % - Declaration: value (1,1) double', ...
    '        value (1,1) double = 0', ...
    '    end', ...
    'end'});

rehash
clear(helperWidgetClassName, typedClassName, variableSizedClassName, typedAnnotatedClassName, annotationOnlyClassName, untypedClassName, hiddenClassName, declaredClassName)

typedDoc = ClassDocumentation(typedClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
typedValueDoc = methodDocumentationNamed(typedDoc, "value");
assert(strcmp(string(typedValueDoc.propertyClassName), "double"), ...
    'Reflected typed properties should expose their MATLAB class name.');
assert(strcmp(string(typedValueDoc.propertySizeText), "(1,1)"), ...
    'Reflected typed properties should expose their fixed size.');
typedDoc.writeToFile();
typedValueText = fileread(fullfile(typedDoc.pathOfClassFolderOnHardDrive, 'value.md'));
assert(contains(typedValueText, "## Type"), ...
    'Typed property pages should render a Type section.');
assert(contains(typedValueText, "+ Class: `double`"), ...
    'Typed property pages should render the reflected class name.');
assert(contains(typedValueText, "+ Size: `(1,1)`"), ...
    'Typed property pages should render fixed sizes in code formatting.');

variableSizedDoc = ClassDocumentation(variableSizedClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
variableSizedValueDoc = methodDocumentationNamed(variableSizedDoc, "values");
assert(strcmp(string(variableSizedValueDoc.propertySizeText), "(1,:)"), ...
    'Reflected typed properties should normalize unrestricted dimensions.');
variableSizedDoc.writeToFile();
variableSizedText = fileread(fullfile(variableSizedDoc.pathOfClassFolderOnHardDrive, 'values.md'));
assert(contains(variableSizedText, "+ Size: `(1,:)`"), ...
    'Variable-sized properties should render unrestricted dimensions in code formatting.');

typedAnnotatedDoc = ClassDocumentation(typedAnnotatedClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
widgetDoc = methodDocumentationNamed(typedAnnotatedDoc, "widget");
assert(strcmp(string(widgetDoc.propertyClassName), helperWidgetClassName), ...
    'Reflected property types should win over annotation fallback types.');
assert(strcmp(string(widgetDoc.propertySizeText), "(1,1)"), ...
    'Reflected property sizes should win over annotation fallback sizes.');

annotationOnlyDoc = ClassDocumentation(annotationOnlyClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
virtualDoc = methodDocumentationNamed(annotationOnlyDoc, "virtualValue");
assert(strcmp(string(virtualDoc.propertyClassName), "TrajectorySpline"), ...
    'Annotation-only object properties should expose annotation class metadata.');
assert(strcmp(string(virtualDoc.propertySizeText), "nonempty vector"), ...
    'Annotation-only object properties should expose annotation size metadata.');
annotationOnlyDoc.writeToFile();
virtualText = fileread(fullfile(annotationOnlyDoc.pathOfClassFolderOnHardDrive, 'virtualvalue.md'));
assert(contains(virtualText, "+ Class: `TrajectorySpline`"), ...
    'Annotation-only property pages should render annotation-supplied class metadata.');
assert(contains(virtualText, "+ Size: nonempty vector"), ...
    'Annotation-only property pages should render freeform size text without code formatting.');

untypedDoc = ClassDocumentation(untypedClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
untypedDoc.writeToFile();
untypedText = fileread(fullfile(untypedDoc.pathOfClassFolderOnHardDrive, 'value.md'));
assert(~contains(untypedText, "## Type"), ...
    'Untyped property pages should not render a Type section.');

hiddenDoc = ClassDocumentation(hiddenClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
hiddenDoc.writeToFile();
assert(~isfile(fullfile(hiddenDoc.pathOfClassFolderOnHardDrive, 'secretvalue.md')), ...
    'Hidden or private typed properties should remain unpublished.');

declaredDoc = ClassDocumentation(declaredClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
declaredDoc.writeToFile();
declaredText = fileread(fullfile(declaredDoc.pathOfClassFolderOnHardDrive, 'value.md'));
assert(contains(declaredText, "## Type"), ...
    'Manual property declarations should not suppress the Type section.');
assert(contains(declaredText, "## Declaration"), ...
    'Manual property declarations should still render their Declaration section.');
assert(contains(declaredText, "value (1,1) double"), ...
    'Manual property declaration text should remain unchanged.');

function cleanup = addPathIfNeeded(pathToAdd)
if contains(path, [pathsep pathToAdd pathsep]) || startsWith(path, [pathToAdd pathsep]) || endsWith(path, [pathsep pathToAdd]) || strcmp(path, pathToAdd)
    cleanup = onCleanup(@() []);
else
    addpath(pathToAdd, '-begin');
    cleanup = onCleanup(@() rmpath(pathToAdd));
end
end

function documentation = methodDocumentationNamed(classDocumentation, name)
index = strcmp(string({classDocumentation.allMethodDocumentation(:).name}), string(name));
assert(nnz(index) == 1, 'Expected exactly one documentation entry named %s.', name);
documentation = classDocumentation.allMethodDocumentation(index);
end

function writeTextFile(path, text)
if ischar(text)
    lines = {text};
elseif isstring(text)
    lines = cellstr(text);
else
    lines = text;
end

fileID = fopen(path, 'w');
assert(fileID >= 0, 'Unable to open %s for writing.', path);
cleanup = onCleanup(@() fclose(fileID)); %#ok<NASGU>
for iLine = 1:numel(lines)
    fprintf(fileID, '%s', lines{iLine});
    if iLine < numel(lines)
        fprintf(fileID, '\n');
    end
end
end

function removeDirectoryIfPresent(pathToRemove)
if isfolder(pathToRemove)
    rmdir(pathToRemove, 's');
end
end
