repoRoot = fileparts(fileparts(mfilename('fullpath')));
cleanupRepoPath = addPathIfNeeded(repoRoot);
cleanupClassAnnotationsPath = addPathIfNeeded('/Users/jearly/Documents/OceanKitRepositories/class-annotations'); %#ok<NASGU>

helperRoot = tempname;
mkdir(helperRoot);
cleanupHelperRoot = onCleanup(@() removeDirectoryIfPresent(helperRoot)); %#ok<NASGU>
cleanupHelperPath = addPathIfNeeded(helperRoot); %#ok<NASGU>

reflectedClassName = 'DocumentationMergeReflectedPropertyTestClass';
hiddenClassName = 'DocumentationMergeHiddenPropertyTestClass';
annotationOnlyClassName = 'DocumentationMergeAnnotationOnlyPropertyTestClass';

writeTextFile(fullfile(helperRoot, strcat(reflectedClassName, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', reflectedClassName), ...
    '    properties', ...
    '        % Reflected property summary.', ...
    '        %', ...
    '        % Reflected property discussion.', ...
    '        %', ...
    '        % - Topic: Reflected topic', ...
    '        value', ...
    '    end', ...
    '    methods', ...
    sprintf('        function self = %s(options)', reflectedClassName), ...
    '            arguments', ...
    '                options.value = 1', ...
    '            end', ...
    '            self.value = options.value;', ...
    '        end', ...
    '    end', ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CANumericProperty(''value'', {''sampleIndex''}, ''m'', ''Annotated property summary.'', detailedDescription=''- Topic: Annotated topic'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''value''};', ...
    '        end', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(hiddenClassName, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', hiddenClassName), ...
    '    properties (Access = private)', ...
    '        % Private property summary.', ...
    '        %', ...
    '        % Private property discussion.', ...
    '        %', ...
    '        % - Topic: Private topic', ...
    '        secretValue', ...
    '    end', ...
    '    methods', ...
    sprintf('        function self = %s(options)', hiddenClassName), ...
    '            arguments', ...
    '                options.secretValue = 1', ...
    '            end', ...
    '            self.secretValue = options.secretValue;', ...
    '        end', ...
    '    end', ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CANumericProperty(''secretValue'', {}, '''', ''Annotated private property.'', detailedDescription=''- Topic: Annotated private topic'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''secretValue''};', ...
    '        end', ...
    '    end', ...
    'end'});

writeTextFile(fullfile(helperRoot, strcat(annotationOnlyClassName, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', annotationOnlyClassName), ...
    '    methods', ...
    sprintf('        function self = %s()', annotationOnlyClassName), ...
    '        end', ...
    '    end', ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CAObjectProperty(''virtualValue'', ''Virtual annotation-only property.'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''virtualValue''};', ...
    '        end', ...
    '    end', ...
    'end'});
writeTextFile(fullfile(helperRoot, 'virtualValue.md'), { ...
    '- Topic: Virtual topic', ...
    'Virtual discussion text.'});

rehash
clear(reflectedClassName, hiddenClassName, annotationOnlyClassName)

reflectedDoc = ClassDocumentation(reflectedClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
valueDocumentation = methodDocumentationNamed(reflectedDoc, "value");
assert(strcmp(valueDocumentation.shortDescription, 'Reflected property summary.'), ...
    'Reflected property summaries should win over annotation descriptions.');
assert(strcmp(valueDocumentation.topic, 'Reflected topic'), ...
    'Reflected property topics should win over annotation topics.');
assert(contains(string(valueDocumentation.detailedDescription), "Reflected property discussion."), ...
    'Reflected property discussion text should be preserved.');
assert(valueDocumentation.functionType == FunctionType.transformProperty, ...
    'Numeric annotations should still contribute transform-property formatting metadata.');
assert(strcmp(string(valueDocumentation.units), "m"), ...
    'Annotation units should enrich reflected property documentation.');
assert(isequal(valueDocumentation.dimensions, {'sampleIndex'}), ...
    'Annotation dimensions should enrich reflected property documentation.');
assert(strcmp(string(valueDocumentation.access), "public"), ...
    'Reflected public access should be preserved when annotations are merged.');
assert(valueDocumentation.isHidden == 0, ...
    'Reflected hidden status should be preserved when annotations are merged.');

overrideDocumentation = MethodDocumentation("value");
overrideDocumentation.shortDescription = "Override summary.";
overrideDocumentation.access = "public";
overrideDocumentation.functionType = FunctionType.instanceProperty;
reflectedDoc.addMethodDocumentation(overrideDocumentation);
valueDocumentation = methodDocumentationNamed(reflectedDoc, "value");
assert(strcmp(valueDocumentation.shortDescription, "Override summary."), ...
    'Explicit addMethodDocumentation overrides should still replace existing documentation.');

hiddenDoc = ClassDocumentation(hiddenClassName, buildFolder=helperRoot, shouldLoadDetailedDescriptionSidecars=false);
secretDocumentation = methodDocumentationNamed(hiddenDoc, "secretValue");
assert(strcmp(string(secretDocumentation.access), "private"), ...
    'Reflected private access should not be replaced by annotation defaults.');
assert(secretDocumentation.isHidden == 0, ...
    'Private properties should preserve their reflected hidden flag.');
hiddenDoc.writeToFile();
assert(~isfile(fullfile(hiddenDoc.pathOfClassFolderOnHardDrive, 'secretvalue.md')), ...
    'Private properties should not be published even when annotations exist.');

annotationOnlyDoc = ClassDocumentation(annotationOnlyClassName, buildFolder=helperRoot);
virtualDocumentation = methodDocumentationNamed(annotationOnlyDoc, "virtualValue");
assert(strcmp(virtualDocumentation.topic, 'Virtual topic'), ...
    'Annotation-only properties should still pick up sidecar-backed topics.');
assert(strcmp(strtrim(virtualDocumentation.detailedDescription), 'Virtual discussion text.'), ...
    'Annotation-only properties should still pick up sidecar-backed discussion text.');
assert(virtualDocumentation.functionType == FunctionType.instanceProperty, ...
    'Annotation-only object properties should be treated as ordinary instance properties.');
annotationOnlyDoc.writeToFile();
assert(isfile(fullfile(annotationOnlyDoc.pathOfClassFolderOnHardDrive, 'virtualvalue.md')), ...
    'Annotation-only properties should still publish successfully.');

function cleanup = addPathIfNeeded(pathToAdd)
if contains(path, [pathsep pathToAdd pathsep]) || startsWith(path, [pathToAdd pathsep]) || endsWith(path, [pathsep pathToAdd]) || strcmp(path, pathToAdd)
    cleanup = onCleanup(@() []);
else
    addpath(pathToAdd, '-begin');
    cleanup = onCleanup(@() rmpath(pathToAdd));
end
end

function documentation = methodDocumentationNamed(classDocumentation, name)
index = strcmp(string({classDocumentation.allMethodDocumentation(:).name}), string(name));
assert(nnz(index) == 1, 'Expected exactly one documentation entry named %s.', name);
documentation = classDocumentation.allMethodDocumentation(index);
end

function writeTextFile(path, text)
if ischar(text)
    lines = {text};
elseif isstring(text)
    lines = cellstr(text);
else
    lines = text;
end

fileID = fopen(path, 'w');
assert(fileID >= 0, 'Unable to open %s for writing.', path);
cleanup = onCleanup(@() fclose(fileID)); %#ok<NASGU>
for iLine = 1:numel(lines)
    fprintf(fileID, '%s', lines{iLine});
    if iLine < numel(lines)
        fprintf(fileID, '\n');
    end
end
end

function removeDirectoryIfPresent(pathToRemove)
if isfolder(pathToRemove)
    rmdir(pathToRemove, 's');
end
end
