metadata = MethodDocumentation("implicitConstructor");
detailedDescription = sprintf([ ...
    'Implicit constructor overview.\n\n', ...
    '- Topic: Create boundary conditions\n', ...
    '- Topic: Place boundary conditions\n', ...
    '- Topic: Inspect boundary conditions\n', ...
    '- Declaration: classdef IMBoundary\n', ...
    '- Declaration: classdef AlternateBoundary\n', ...
    '- nav_order: 3\n', ...
    '- nav_order: 9\n', ...
    '- Developer: false\n', ...
    '- Developer: true\n', ...
    '- Parameter first: first parameter\n', ...
    '- Parameter second: second parameter\n', ...
    '- Returns primary: primary return\n', ...
    '- Returns secondary: secondary return\n']);

metadata.addMetadataFromDetailedDescription(detailedDescription);

assert(strcmp(metadata.topic, "Create boundary conditions"), ...
    'Multiple topic declarations should use the first topic instead of throwing.');
assert(strcmp(metadata.declaration, " classdef IMBoundary"), ...
    'The first declaration should win when scalar metadata is repeated.');
assert(metadata.nav_order == 3, ...
    'The first navigation order should win when scalar metadata is repeated.');
assert(~metadata.isDeveloper, ...
    'The first developer flag should win when scalar metadata is repeated.');
assert(numel(metadata.parameters) == 2 && strcmp(metadata.parameters(1).name, "first") && strcmp(metadata.parameters(2).name, "second"), ...
    'Parameter metadata should remain repeatable and preserve source order.');
assert(numel(metadata.returns) == 2 && strcmp(metadata.returns(1).name, "primary") && strcmp(metadata.returns(2).name, "secondary"), ...
    'Return metadata should remain repeatable and preserve source order.');
assert(contains(string(metadata.detailedDescription), "Implicit constructor overview."), ...
    'Discussion text should be preserved.');
assert(all(~contains(string(metadata.detailedDescription), ["- Topic:", "- Declaration:", "- nav_order:", "- Developer:", "- Parameter ", "- Returns "])), ...
    'All parsed metadata tokens should be stripped from the discussion text.');
