repoRoot = fileparts(fileparts(mfilename('fullpath')));
cleanupRepoPath = addPathIfNeeded(repoRoot); %#ok<NASGU>

helperRoot = tempname;
mkdir(helperRoot);
cleanupHelperRoot = onCleanup(@() removeDirectoryIfPresent(helperRoot)); %#ok<NASGU>
cleanupHelperPath = addPathIfNeeded(helperRoot); %#ok<NASGU>

executionCountPath = fullfile(helperRoot, 'execution-count.txt');
movieBuildCountPath = fullfile(helperRoot, 'movie-build-count.txt');
tutorialPath = fullfile(helperRoot, 'CacheDemo.m');

writeTextFile(fullfile(helperRoot, 'tutorialCacheHelperIncrement.m'), { ...
    'function tutorialCacheHelperIncrement(counterPath)', ...
    'counterPath = string(counterPath);', ...
    'count = 0;', ...
    'if isfile(counterPath)', ...
    '    storedCount = str2double(strtrim(fileread(counterPath)));', ...
    '    if ~isnan(storedCount)', ...
    '        count = storedCount;', ...
    '    end', ...
    'end', ...
    'fileID = fopen(counterPath, "w");', ...
    'assert(fileID ~= -1, "Could not open counter file for writing.");', ...
    'cleanup = onCleanup(@() fclose(fileID)); %#ok<NASGU>', ...
    'fprintf(fileID, "%d", count + 1);', ...
    'end'});

writeTextFile(fullfile(helperRoot, 'tutorialCacheHelperWriteMovie.m'), { ...
    'function tutorialCacheHelperWriteMovie(moviePath, posterPath, counterPath)', ...
    'moviePath = string(moviePath);', ...
    'posterPath = string(posterPath);', ...
    'tutorialCacheHelperIncrement(counterPath);', ...
    'fileID = fopen(moviePath, "w");', ...
    'assert(fileID ~= -1, "Could not open movie output for writing.");', ...
    'cleanupMovie = onCleanup(@() fclose(fileID)); %#ok<NASGU>', ...
    'fprintf(fileID, "demo movie");', ...
    'if posterPath ~= ""', ...
    '    imwrite(uint8(255), posterPath);', ...
    'end', ...
    'end'});

writeTutorialSource(tutorialPath, executionCountPath, movieBuildCountPath, "");

buildFolder1 = fullfile(helperRoot, 'build1');
buildTutorial(tutorialPath, buildFolder1, "", helperRoot, false);
assertCounterValue(executionCountPath, 1, ...
    'The first tutorial build should execute the tutorial once.');
assertCounterValue(movieBuildCountPath, 1, ...
    'The first tutorial build should create the movie once.');
assertTutorialOutputsExist(buildFolder1);

buildFolder2 = fullfile(helperRoot, 'build2');
buildTutorial(tutorialPath, buildFolder2, buildFolder1, helperRoot, false);
assertCounterValue(executionCountPath, 1, ...
    'An unchanged tutorial should reuse the previous build without re-executing.');
assertCounterValue(movieBuildCountPath, 1, ...
    'Whole-tutorial reuse should skip movie generation as well.');
assertTutorialOutputsExist(buildFolder2);

writeTutorialSource(tutorialPath, executionCountPath, movieBuildCountPath, ...
    '% Updated prose to invalidate the source hash.');

buildFolder3 = fullfile(helperRoot, 'build3');
buildTutorial(tutorialPath, buildFolder3, buildFolder2, helperRoot, false);
assertCounterValue(executionCountPath, 2, ...
    'Editing the tutorial source should invalidate the whole-tutorial stamp.');
assertCounterValue(movieBuildCountPath, 2, ...
    'When the tutorial reruns after a source edit, the movie should rebuild.');
assertTutorialOutputsExist(buildFolder3);

buildFolder4 = fullfile(helperRoot, 'build4');
buildTutorial(tutorialPath, buildFolder4, buildFolder3, helperRoot, true);
assertCounterValue(executionCountPath, 3, ...
    'rebuildTutorials=true should force tutorial execution even when the source matches.');
assertCounterValue(movieBuildCountPath, 2, ...
    'Forced tutorial execution should still reuse the prior movie when its movie stamp matches.');
assertTutorialOutputsExist(buildFolder4);

previousMissingMarkdown = fullfile(helperRoot, 'previous-missing-markdown');
copyfile(buildFolder4, previousMissingMarkdown);
delete(fullfile(previousMissingMarkdown, 'tutorials', 'cache-demo.md'));

buildFolder5 = fullfile(helperRoot, 'build5');
buildTutorial(tutorialPath, buildFolder5, previousMissingMarkdown, helperRoot, false);
assertCounterValue(executionCountPath, 4, ...
    'Missing previous markdown should force tutorial execution.');
assertCounterValue(movieBuildCountPath, 2, ...
    'Movie reuse should still work when execution is forced by missing markdown.');
assertTutorialOutputsExist(buildFolder5);

previousMissingStamp = fullfile(helperRoot, 'previous-missing-stamp');
copyfile(buildFolder4, previousMissingStamp);
delete(fullfile(previousMissingStamp, 'tutorials', 'cache-demo.build-stamp.json'));

buildFolder6 = fullfile(helperRoot, 'build6');
buildTutorial(tutorialPath, buildFolder6, previousMissingStamp, helperRoot, false);
assertCounterValue(executionCountPath, 5, ...
    'Missing previous build stamps should force tutorial execution.');
assertCounterValue(movieBuildCountPath, 2, ...
    'Movie reuse should still work when execution is forced by a missing build stamp.');
assertTutorialOutputsExist(buildFolder6);

function buildTutorial(tutorialPath, buildFolder, previousBuildFolder, helperRoot, rebuildTutorials)
tutorialDocumentation = TutorialDocumentation.documentationFromSourceFiles( ...
    tutorialPath, ...
    buildFolder=buildFolder, ...
    previousBuildFolder=previousBuildFolder, ...
    sourceRoot=helperRoot, ...
    executionPaths=string(helperRoot), ...
    rebuildTutorials=rebuildTutorials);
tutorialDocumentation.writeToFile();
end

function writeTutorialSource(tutorialPath, executionCountPath, movieBuildCountPath, extraNarrativeLine)
lines = { ...
    '%% Tutorial Metadata', ...
    '% Title: Cache demo', ...
    '% Slug: cache-demo', ...
    '% Description: Exercise source-stamped tutorial caching.', ...
    '', ...
    '%% Build cache behavior', ...
    '% This tutorial exists only to exercise tutorial caching behavior.', ...
    extraNarrativeLine, ...
    sprintf('executionCountPath = "%s";', executionCountPath), ...
    sprintf('movieBuildCountPath = "%s";', movieBuildCountPath), ...
    'tutorialCacheHelperIncrement(executionCountPath);', ...
    'x = linspace(0, 1, 5);', ...
    'figure', ...
    'plot(x, x.^2, LineWidth=1.5)', ...
    'xlabel("x")', ...
    'ylabel("x^2")', ...
    'if exist("tutorialFigureCapture", "var") && isa(tutorialFigureCapture, "function_handle")', ...
    '    tutorialFigureCapture("demo-figure", Caption="A small figure for cache testing.");', ...
    'end', ...
    'if exist("tutorialMovieCapture", "var") && isa(tutorialMovieCapture, "function_handle")', ...
    '    tutorialMovieCapture( ...', ...
    '        "demo.mp4", ...', ...
    '        Caption="A small movie for cache testing.", ...', ...
    '        Poster="demo-poster.png", ...', ...
    '        Settings=struct("FrameRate", 12), ...', ...
    '        Build=@(moviePath, posterPath) tutorialCacheHelperWriteMovie(moviePath, posterPath, movieBuildCountPath));', ...
    'end'};
writeTextFile(tutorialPath, lines);
end

function assertTutorialOutputsExist(buildFolder)
tutorialRoot = fullfile(buildFolder, 'tutorials');
assert(isfile(fullfile(tutorialRoot, 'cache-demo.md')), ...
    'Expected the tutorial markdown page to exist after the build.');
assert(isfile(fullfile(tutorialRoot, 'cache-demo.build-stamp.json')), ...
    'Expected the tutorial build stamp to exist after the build.');
assert(isfile(fullfile(tutorialRoot, 'cache-demo', 'demo-figure.png')), ...
    'Expected the generated figure to exist after the build.');
assert(isfile(fullfile(tutorialRoot, 'cache-demo', 'demo.mp4')), ...
    'Expected the generated movie to exist after the build.');
assert(isfile(fullfile(tutorialRoot, 'cache-demo', 'demo.mp4.stamp.json')), ...
    'Expected the generated movie stamp to exist after the build.');
assert(isfile(fullfile(tutorialRoot, 'cache-demo', 'demo-poster.png')), ...
    'Expected the generated movie poster to exist after the build.');
end

function assertCounterValue(counterPath, expectedValue, failureMessage)
assert(isfile(counterPath), 'Expected the counter file %s to exist.', counterPath);
actualValue = str2double(strtrim(fileread(counterPath)));
assert(actualValue == expectedValue, failureMessage);
end

function cleanup = addPathIfNeeded(pathToAdd)
if contains(path, [pathsep pathToAdd pathsep]) || startsWith(path, [pathToAdd pathsep]) ...
        || endsWith(path, [pathsep pathToAdd]) || strcmp(path, pathToAdd)
    cleanup = onCleanup(@() []);
else
    addpath(pathToAdd, '-begin');
    cleanup = onCleanup(@() rmpath(pathToAdd));
end
end

function writeTextFile(path, text)
if ischar(text)
    lines = {text};
elseif isstring(text)
    lines = cellstr(text);
else
    lines = text;
end

fileID = fopen(path, 'w');
assert(fileID >= 0, 'Unable to open %s for writing.', path);
cleanup = onCleanup(@() fclose(fileID)); %#ok<NASGU>
for iLine = 1:numel(lines)
    fprintf(fileID, '%s', lines{iLine});
    if iLine < numel(lines)
        fprintf(fileID, '\n');
    end
end
end

function removeDirectoryIfPresent(pathToRemove)
if isfolder(pathToRemove)
    rmdir(pathToRemove, 's');
end
end
