repoRoot = fileparts(fileparts(mfilename('fullpath')));
cleanupRepoPath = addPathIfNeeded(repoRoot);
cleanupClassAnnotationsPath = addPathIfNeeded('/Users/jearly/Documents/OceanKitRepositories/class-annotations'); %#ok<NASGU>

helperRoot = tempname;
mkdir(helperRoot);
cleanupHelperRoot = onCleanup(@() removeDirectoryIfPresent(helperRoot)); %#ok<NASGU>
cleanupHelperPath = addPathIfNeeded(helperRoot); %#ok<NASGU>

className = 'DocumentationSidecarAnnotatedTestClass';
writeTextFile(fullfile(helperRoot, strcat(className, '.m')), { ...
    sprintf('classdef %s < CAAnnotatedClass', className), ...
    '    properties', ...
    '        value', ...
    '    end', ...
    '    methods', ...
    sprintf('        function self = %s(options)', className), ...
    '            arguments', ...
    '                options.value = 1', ...
    '            end', ...
    '            self.value = options.value;', ...
    '        end', ...
    '    end', ...
    '    methods (Static)', ...
    '        function propertyAnnotations = classDefinedPropertyAnnotations()', ...
    '            propertyAnnotations = CAPropertyAnnotation.empty(0,0);', ...
    '            propertyAnnotations(end+1) = CANumericProperty(''value'', {}, '''', ''test value property'');', ...
    '        end', ...
    '        function names = classRequiredPropertyNames()', ...
    '            names = {''value''};', ...
    '        end', ...
    '    end', ...
    'end'});
writeTextFile(fullfile(helperRoot, 'value.md'), { ...
    '- Topic: Sidecar Topic', ...
    'Sidecar discussion text.'});
rehash
clear(className)

propertyAnnotations = feval(className + ".classDefinedPropertyAnnotations");
assert(numel(propertyAnnotations) == 1, 'The temporary annotated class should expose one property annotation.');
assert(isempty(propertyAnnotations(1).detailedDescription), ...
    'Ordinary annotation construction should not load detailedDescription sidecars.');

methodDocumentation = ClassDocumentation.methodDocumentationFromAnnotatedClass(className);
assert(numel(methodDocumentation) == 1, ...
    'Annotated property documentation should be returned for the temporary annotated class.');
assert(strcmp(methodDocumentation(1).topic, 'Sidecar Topic'), ...
    'Documentation builders should load topic metadata from annotation sidecars by default.');
assert(strcmp(strtrim(methodDocumentation(1).detailedDescription), 'Sidecar discussion text.'), ...
    'Documentation builders should load detailed annotation discussion text from sidecars by default.');

methodDocumentationWithoutSidecars = ClassDocumentation.methodDocumentationFromAnnotatedClass( ...
    className, shouldLoadDetailedDescriptionSidecars=false);
assert(numel(methodDocumentationWithoutSidecars) == 1, ...
    'Annotated property documentation should still be returned when sidecar loading is disabled.');
assert(isempty(methodDocumentationWithoutSidecars(1).topic), ...
    'Disabling documentation sidecars should suppress sidecar-backed topic metadata.');
assert(isempty(methodDocumentationWithoutSidecars(1).detailedDescription), ...
    'Disabling documentation sidecars should suppress sidecar-backed detailed discussion text.');

function cleanup = addPathIfNeeded(pathToAdd)
if contains(path, [pathsep pathToAdd pathsep]) || startsWith(path, [pathToAdd pathsep]) || endsWith(path, [pathsep pathToAdd]) || strcmp(path, pathToAdd)
    cleanup = onCleanup(@() []);
else
    addpath(pathToAdd, '-begin');
    cleanup = onCleanup(@() rmpath(pathToAdd));
end
end

function writeTextFile(path, text)
if ischar(text)
    lines = {text};
elseif isstring(text)
    lines = cellstr(text);
else
    lines = text;
end

fileID = fopen(path, 'w');
assert(fileID >= 0, 'Unable to open %s for writing.', path);
cleanup = onCleanup(@() fclose(fileID)); %#ok<NASGU>
for iLine = 1:numel(lines)
    fprintf(fileID, '%s', lines{iLine});
    if iLine < numel(lines)
        fprintf(fileID, '\n');
    end
end
end

function removeDirectoryIfPresent(pathToRemove)
if isfolder(pathToRemove)
    rmdir(pathToRemove, 's');
end
end
